package com.sms.moLotus.feature.settings.autogeneratedmessage

import android.content.Context
import android.widget.Toast
import com.sms.moLotus.common.base.QkViewModel
import com.sms.moLotus.interactor.SendMessage
import com.sms.moLotus.repository.ConversationRepository
import com.uber.autodispose.android.lifecycle.scope
import com.uber.autodispose.autoDisposable
import javax.inject.Inject
import javax.inject.Named

class SettingsViewModel @Inject constructor(
    @Named("threadId") private val threadId: Long,

    private val conversationRepo: ConversationRepository,
    private val context: Context,
    private val sendMessage: SendMessage
) : QkViewModel<SettingsView, SettingsState>(SettingsState(page = Inbox(data = conversationRepo.getConversations()))) {

    override fun bindView(view: SettingsView) {
        super.bindView(view)

        view.composeIntent
            .autoDisposable(view.scope())
            .subscribe {
                val list: ArrayList<String> = ArrayList()
                list.add("3000")
                Toast.makeText(context, "SMS sent", Toast.LENGTH_SHORT).show()
                sendMessage.execute(
                    SendMessage.Params(
                        0, threadId, list, "MMS",
                        listOf(), 0
                    )
                )
/*                sendMessage.execute(
                    SendMessage.Params(
                        0, threadId, list, "MMS ${Build.MODEL}",
                        listOf(), 0
                    )
                )*/
            }
    }

}