package com.sms.moLotus.feature.settings.autogeneratedmessage

import androidx.lifecycle.ViewModel
import com.sms.moLotus.feature.settings.AppSettingsActivity
import com.sms.moLotus.injection.ViewModelKey
import dagger.Module
import dagger.Provides
import dagger.multibindings.IntoMap
import javax.inject.Named

@Module
class SettingsActivityModule {


    @Provides
    @Named("threadId")
    fun provideThreadId(activity: AppSettingsActivity): Long =
        activity.intent.extras?.getLong("threadId") ?: 0L

    @Provides
    @IntoMap
    @ViewModelKey(SettingsViewModel::class)
    fun provideMainViewModel(viewModel: SettingsViewModel): ViewModel = viewModel

}