package com.sms.moLotus.feature.settings.autogeneratedmessage

import com.sms.moLotus.common.base.QkView
import io.reactivex.Observable

interface SettingsView : QkView<SettingsState> {

    val composeIntent: Observable<Unit>


}
